# Generated by cucumber-sinatra. (2014-04-08 10:31:01 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'bagit-server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = BagitServer

class BagitServerWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
  include Rack::Test

  def app
    Capybara.app
  end

end

World do
  BagitServerWorld.new
end
